### ISSUE TITLE
[BUG]: Missing data in PyPI package

### ISSUE THREAD

**Issue by VarIr** [Fraunhofer-ITMP/PEMT#1]
**Describe the bug**
The chemical extractor fails due to a missing `chembl_uniprot_mapping.txt` file. It seems installing from PyPI omits the `data` directory.
After manually copying data files from the github repo to the expected directory, the error is gone (and the tool runs into a probably unrelated 500 internal server error by ebi.ac.uk).

**To Reproduce**
``` bash
conda create --prefix /tmp/pemt python=3.8
conda activate /tmp/pemt
pip install PEMT
pemt run-chemical-extractor --name=symbol --data=/tmp/symbol.tsv  --uniprot
```

**Expected behavior**
Program run with exit code 0.

**Error**
``` 
Starting the chemical extractor pipeline for symbol
Traceback (most recent call last):
  File "/tmp/pemt/bin/pemt", line 8, in <module>
    sys.exit(main())
  File "/tmp/pemt/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/pemt/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/pemt/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/pemt/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/pemt/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/pemt/lib/python3.8/site-packages/pemt/cli.py", line 98, in run_chemical_extractor
    gene_chemical_dict = extract_chemicals(
  File "/tmp/pemt/lib/python3.8/site-packages/pemt/chemical_extractor/experimental_data_extraction.py", line 138, in extract_chemicals
    chembl_mapper = pd.read_csv(
  File "/tmp/pemt/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/tmp/pemt/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/tmp/pemt/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/tmp/pemt/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/tmp/pemt/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/tmp/pemt/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/tmp/pemt/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/tmp/pemt/lib/python3.8/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pemt/lib/python3.8/site-packages/pemt/../../data/mapper/chembl_uniprot_mapping.txt'
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by YojanaGadiya** [comment]
@VarIr thank you for reporting this. I will also take a look and add the data directory as part of the PyPi. 

Related to the 500 Server error from EBI, I have an issue open with EBI. I am hoping to get it solved - https://github.com/chembl/chembl_webresource_client/issues/120

**Comment by YojanaGadiya** [comment]
@VarIr the next patch 0.0.3-dev is supposed to fix this issue. In case the issue still persists, please let me know. Thank You.
